version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5000
    container_name: ProdutosFront
    ports:
      - "5001:80"
    restart: unless-stopped
